asset_path: /app/outputs/demo_video/simulation/1_pen_optimized.glb
usd_dir: /app/outputs/demo_video/simulation
usd_file_name: 1_pen_optimized.usd
force_usd_conversion: true
make_instanceable: false
mass_props:
  mass: 1.0
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: false
  disable_gravity: false
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: 0.006
  rest_offset: -0.002
  torsional_patch_radius: 0.05
  min_torsional_patch_radius: 0.005
collision_approximation: convexDecomposition
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-11-29 at 20:32:27.
##
